### ISSUE TITLE
authorize user Piwigo-TranslationTeam

### ISSUE THREAD

**Issue by ddtddt** [7tonin/piwigo-stereoZoom#3]
Hi :-)

For add your project on https://piwigo.org/translate, can you give acces to user Piwigo-TranslationTeam and say me it's ok ;-)

in settings / Manage access
invite a collaborator
Piwigo-TranslationTeam

**Comment by 7tonin** [comment]
...
It's OK !

**Comment by 7tonin** [comment]
Previous invitation, expired, has been removed. 
A brand new one has just been sent. 🚀 🎊 🎉

**Comment by 7tonin** [comment]
first translations released
success !
Thank you
